name: Test Version Bumping

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches:
      - main

jobs:
  test-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install bump-my-version
        run: |
          python -m pip install --upgrade pip
          pip install bump-my-version

      - name: Show current version
        run: |
          echo "Current version in pyproject.toml:"
          bump-my-version show current_version
          
          echo "Latest git tag:"
          git describe --tags --abbrev=0 2>/dev/null || echo "No tags found"

      - name: Test version bump (dry run)
        run: |
          echo "Testing patch bump (dry run):"
          bump-my-version bump patch --dry-run
          
          echo "Testing minor bump (dry run):"
          bump-my-version bump minor --dry-run
          
          echo "Testing major bump (dry run):"
          bump-my-version bump major --dry-run

      - name: Show commit history
        run: |
          echo "Last 10 commits:"
          git log --oneline -10
          
          echo "Commits since last tag:"
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          git log $LAST_TAG..HEAD --oneline 2>/dev/null || echo "No commits since last tag"
