name: Auto Version & Tag

on:
  push:
    branches:
      - main  # Trigger on pushes to main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for tags and history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump-my-version

      - name: Determine bump type from commit messages
        id: bump
        run: |
          COMMITS=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s")
          echo "Commits since last tag:"
          echo "$COMMITS"

          if echo "$COMMITS" | grep -q "BREAKING CHANGE"; then
            echo "BUMP=major" >> $GITHUB_ENV
          elif echo "$COMMITS" | grep -qE "^feat"; then
            echo "BUMP=minor" >> $GITHUB_ENV
          elif echo "$COMMITS" | grep -qE "^fix"; then
            echo "BUMP=patch" >> $GITHUB_ENV
          else
            echo "No version bump needed"
            exit 0
          fi

      - name: Bump version
        run: |
          # Auto bump based on commit type: default to minor if none
          BUMP=${BUMP:-minor}
          echo "Bumping version ($BUMP)"
          bump-my-version bump $BUMP --message "chore: bump version"

      - name: Commit version bump and create tag
        run: |
          VERSION=$(bump-my-version show current_version)
          if git diff --quiet; then
            echo "No changes detected, skipping commit and tag."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: bump version to $VERSION"
            git tag v$VERSION
            git push origin main --tags
          fi
